# Generated by Django 5.1.2 on 2024-10-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'Advanced Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('LINUX', 'Linux Administration'), ('OS', 'Operating Systems'), ('MP', 'Mathematical programming'), ('DBMS', 'Database Management Systems'), ('MERN', 'MERN Stack Development'), ('CC', 'Cloud Computing')], max_length=50)),
                ('section', models.CharField(choices=[('S11', 'Section S11'), ('S12', 'Section S12'), ('S13', 'Section S13'), ('S14', 'Section S14'), ('S15', 'Section S15')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.studentlist')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'Advanced Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('LINUX', 'Linux Administration'), ('OS', 'Operating Systems'), ('MP', 'Mathematical programming'), ('DBMS', 'Database Management Systems'), ('MERN', 'MERN Stack Development'), ('CC', 'Cloud Computing')], max_length=50)),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.studentlist')),
            ],
        ),
    ]
